services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: booking-bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    
  bot:
    build: .
    command: sh -c "python -m bot.database.scripts --create && python -m bot"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .docker-env
volumes:
  postgres_data:
